### ISSUE TITLE
Autoselection not working in 27.2 when no speakers selected

### ISSUE THREAD

**Issue by floogs** [ejurgensen/forked-daapd#1091]
I have two AirPlay speakers that I use with forked-daapd and the iOS Remote app: a Sonos that stays on all the time, and a Sony receiver that's only on when it's in use.

Previous behavior for forked-daapd was that if I was last playing music to the Sony and then turned it off, the next time I played music it would default to the Sonos without any interaction on my part.

Since upgrading to the forked-daapd 27.2 release, this same situation now results in playback appearing to start in Remote, but no audio from the Sonos. The music is technically playing as the timeline ticks down as normal, but I have to open the web interface and manually switch to the Sonos to actually direct the audio to it (at which point it starts playing mid-song). This seems to me like it's defaulting to playback in the web interface. In typical Apple fashion, the Remote app removes the speaker selection entirely if it only detects one AirPlay device, so switching speakers via the app isn't an option.

Could this be the result of the new speaker selection logic in 27.2 per below? I also redid my config file from scratch when I upgraded to 27.2, so it's possible my config is at fault. In either case I didn't want to file this as a bug before ruling out these other issues; any help appreciated.

```
- new speaker selection logic (persist user choice even after failure)
- speaker autoselect no longer enabled by default
```

**Comment by ejurgensen** [comment]
Yes, you are entirely right. I have a setup not unlike yours: A Sony that gets switched on/off and which I mostly use when listening to something, and then a few other Airplay devices I don't usually use. I changed the speaker selection in 27.2, because the selection of the Sony was lost when switched off and then on again, and instead speakers I didn't want got enabled.

If you want, you can enable speaker_autoselect in the config and you should then get back to the behavior where your Sonos gets selected when the Sony can't be activated.

> In typical Apple fashion, the Remote app removes the speaker selection entirely if it only detects one AirPlay device, so switching speakers via the app isn't an option.

I wasn't aware of that. You should be able to get around that by enabling local audio. You can just set the type to "dummy". That way there will be two speakers, so that you get the option in Remote.

**Comment by floogs** [comment]
Thanks, that helps clear up the new behavior behind the scenes. I'll turn the autoselect back on for now.

Is it currently possible to set a speaker priority list? Some kind of simple user-configurable hierarchy such as "if the Sony is available, play to that; otherwise default to the Sonos" (to use my setup as an example) could be the most hands-free way to set up a permanent device config, although I don't know how much trouble that would be to implement.

On your last point, rather than making a dummy device to keep the AirPlay list populated, it seems you could also enable `permanent` in the per-device AirPlay settings for speakers that aren't always turned on, to keep them present in the list. Though I don't know what the consequences would be if you inadvertently tried to target playback to a nonexistent device.

**Comment by ejurgensen** [comment]
Yes, you can also use the "permanent" option. I don't use that because I like to know if the Sony is ready or not.

I think most users want playback to start on a specific device, and not any other, so I'm not going to add a priority list feature. However, when you have autoselect enabled, forked-daapd will prioritize Airplay devices first, and I think it then tries to select alphabetically. So you can in a way set priorities via the names.

**Comment by floogs** [comment]
It seems enabling device autoselect hasn't fixed this issue -- even after a fresh restart of forked-daapd and with only the Sonos on, I'm still getting the "silent" playback issue in the Remote app, and have to go into the web interface to toggle the Sonos on manually, as before.

This is what I first see in the web interface in the above scenario (Bedroom Arc is the Sonos device). Clicking the icon next to the Sonos' volume slider toggles it on and audio then starts instantly.

![image](https://user-images.githubusercontent.com/38588287/92287968-24fe5280-eec0-11ea-9053-575326d43974.png)

Is there something else I could be missing in my config?

**Comment by ejurgensen** [comment]
Indeed, there is a bug :-(

I see now that when I changed this, I only tested autoselection of another speaker when a selected speaker immediately fails, not when there are no selected speakers. And in that case autoselection actually does not kick in, contrary to what I said, and contrary to earlier versions. So I will have to fix that.

**Comment by ejurgensen** [comment]
Should be fixed now, if you have the opportunity to test it then please let me know of the results

**Comment by floogs** [comment]
Sure, I'm building the new version now and will report back when I get a chance to test it out. Thanks for the quick fix.

In the interest of not cluttering up the issues list, I wanted to run another quick question by you: forked-daapd has never been able to detect changes to my library in real time and automatically rescan it. My library isn't hosted on a network share, which per your readme sounds like the scenario that would usually prevent that from working (though for what it's worth, I do run it in a FreeNAS jail, with the library on a ZFS storage pool on the same machine that's mounted in the jail, so perhaps that's why).

Does this seem like something fixable (or even worth the effort of investigating)? I use the manual update process on a cronjob as described in the readme, which is an okay workaround, but obviously not quite as seamless as having the library update instantly. If this is too much of an edge case to be easily fixable I won't open a new issue for it, but wanted to get your thoughts first.

**Comment by ejurgensen** [comment]
On FreeBSD forked-daapd uses [libinotify](https://www.freshports.org/devel/libinotify) to monitor for changes. I don't know if it will work with your setup. If it doesn't there isn't much to do about it, I think. The easiest way to find out is to set the log level to debug, and then 1) copy a file in to the library, check if the log says anything (you can monitor with `tail -f [logfile]`), 2) use `touch` to modify a file in the library and again check if the log says anything. The log messages should say something like "File event" or "Directory event".

**Comment by floogs** [comment]
It seems I'm still having the same issue with speaker selection and/or playback after the fix; audio still appears to be playing but with no sound when I start a song after the previous output device is no longer available.

Though, since I enabled the dummy output device (meaning the active device visible is at least visible in Remote at all times) I can see that now playback is indeed being targeted to the Sonos automatically once the Sony is no longer available, it's just that nothing comes out of the speaker. So maybe there's a problem other than speaker selection at work here? Changing the output device from the Sonos to the dummy and then back did fix the playback in this case.

Thanks for the info about the library monitoring -- I'll try some testing there when I get some more time.

**Comment by ejurgensen** [comment]
> I can see that now playback is indeed being targeted to the Sonos automatically once the Sony is no longer available, it's just that nothing comes out of the speaker

Can you attach some logging (at debug level)? Just from the point where you start playback. I would like to see what is going on.

**Comment by floogs** [comment]
Sorry for the delay here, life got busy.

I actually managed to reproduce this behavior without having to juggle speakers back and forth as I described before -- it turns out that merely starting a fresh instance of forked-daapd also causes the same issue, initially playing no audio from the Sony receiver (which it does defauls to), until I manually change to the dummy output device in Remote and then back to the Sony. And the Sony's front LED always indicates what mode it's in, so I can confirm that it doesn't display "AirPlay" in that first instance until I've switched back to it, which suggests it isn't even making a proper connection to the server until I force it manually.

I've attached a debug log from that fresh start through this playback routine, in case there's anything valuable in the initial startup process. Doing a find for "AVR-DN840" will take you directly to the point where I tried to start playback.

I was also a bit mistaken about my other question regarding auto-scanning new or updated files in the library -- forked-daapd does detect those changes in FreeBSD and scans the files, but it's having trouble updating the metadata correctly in its library (I've got a Remote screenshot illustrating the problem). This same debug log I've attached also has an example of that behavior, though would it be better to open a separate issue to hash that question out, instead of mixing up both issues here?

[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/5252857/forked-daapd.log)

**Comment by ejurgensen** [comment]
Yes, I can see I didn't fix it very well. Will give it another shot!

**Comment by ejurgensen** [comment]
With the above commit I hope the issue is now actually fixed.

Regarding the scanning it would indeed be good to have in a separate issue.

**Comment by ejurgensen** [comment]
Oh man, forgot to remove some test code in the commit. Added yet a commit to fix that.

**Comment by floogs** [comment]
Success! I tried two restarts, once with the Sony on and then with it off, and in both cases the music played immediately, on the Sony in the former case and the Sonos in the latter. Thanks for the fix.

I did notice that when I play music from the Sonos, and then later turn on the Sony and play something else, it stays set to output to the Sonos and I have to change to the Sony manually (despite renaming it to appear first alphabetically). Is that intended behavior?

I also started another issue about the metadata problems I've been having: https://github.com/ejurgensen/forked-daapd/issues/1100

**Comment by ejurgensen** [comment]
> I did notice that when I play music from the Sonos, and then later turn on the Sony and play something else, it stays set to output to the Sonos and I have to change to the Sony manually (despite renaming it to appear first alphabetically). Is that intended behavior?

Depends on whether you selected the Sony prior to switching it off. Maybe easiest to explain intented behaviour with examples:
1. Play on Sony
2. Switch off Sony (playback stops)
3. Start playback, Sonos will be selected
4. Stop playback
5. Switch on Sony
6. Start playback -> both Sonos and Sony should play

Autoselection only takes effect is there no selected speaker or the selected speakers fail immediately. So if you had not selected the Sony previously, and the Sonos is selected and works, the Sony will not be autoselected.

I'm thinking of changing this stuff so it is on speaker level instead. So each speaker would have two options:
selected -> simply means that it is always selected, it cannot be unselected
fallback -> means that we select this speaker if no other is selected and working

Would that make more sense?

**Comment by floogs** [comment]
That (somewhat selfishly) sounds good to me as it would probably enable the use case I'm looking for, i.e. if the Sony is on, play on the Sony only; if it's not, play on the Sonos only. I assume you'd still be able to manually override to select both at the same time, etc.?

**Comment by ejurgensen** [comment]
Yes, but you wouldn't be able to unselect the Sony except by turning it off. Maybe that is bit too drastic, might be better to do it like this:
preferred -> automatically select when device appears
fallback -> select this speaker if no other is selected and working

**Comment by floogs** [comment]
That sounds perfect to me.

As of now, if output has last fallen back to the Sonos and then I later turn on the Sony, f-d defaults to outputting on both. My ideal scenario would instead be for only the preferred speaker to play when it's available, and for only the fallback speaker to play when the preferred isn't there, which sounds like what you're describing here.
