### ISSUE TITLE
Startup is dependend of IPv6 in Debian

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#214]
I just tried to disable iPv6 in Raspbian jessie (trying to deal with some other issues) and noticed that forked-daapd fails with "httpd: could not bind  :::3689".
With IP6 reenabled, everything works as expected.

**Comment by ejurgensen** [comment]
What version of forked-daapd are you using? I think this is fixed in trunk. Also in my Raspbian edition(https://www.raspberrypi.org/forums/viewtopic.php?t=49928), I believe.

**Comment by sparklyballs** [comment]
i saw this too in the docker for forked-daapd
unraid which doesn't support ipv6, the app started failing recently.

conversely, with ipv6 set to no in the config file which fixed the app in unraid, in my ubuntu vm which does support ipv6, with ipv6 set to no, was still getting an ipv6 address.

**Comment by LordMyschkin** [comment]
I am using the one provided by your Raspian distro, 23.3.

**Comment by ejurgensen** [comment]
Yes, I see that the commit that should fix this (https://github.com/ejurgensen/forked-daapd/commit/6cabbc4ab7090837a2afc0d96cee715e1f4e1eb3) is right after my latest Raspbian release. So hopefully this should be fixed with the next release. If any of you experience problems with newer versions please let me know.

**Comment by LordMyschkin** [comment]
With self-compiled 23.4, it works. I even can pailr with remote (found the helper script, should be mentioned in documentation, in my humble opinion).
I'd LOVE to test the mpd-modifications of chme, but I am unable to merge the files myself - my bulk library scan just took 847 seconds, and most mpd-clients timeout after connection.

**Comment by ejurgensen** [comment]
Good point on the documentation, I've made a mention in the README of the script. I've also made a new Raspbian release, so it is now version 23.4.

It would be great if you would test chme's modifications. They merged ok for me. Here is a branch with his modifications that is up to date with master: https://github.com/ejurgensen/forked-daapd/tree/chme-mpddb

**Comment by ejurgensen** [comment]
BTW a scan time of 847 is normal for the very first scan and won't be improved by chme's modifications. It is only the first scan that can be slow. The next time you start forked-daapd you should see it complete much quicker.

**Comment by LordMyschkin** [comment]
Well, you were definitly right. I installed the new version yesterday and deleteted the database - it took more than 7673 seconds to rebuild (37000 files, rPi 2). 
ncmpd seems a little bit more responsive,  mPaD on my iPad does not work anymore - keeps "loading" for hours; Auremo on windows does not cause a "listalll not supported" log entry, but "Error from buffered event:Die Verbindung wurde vom Kommunikationspartner zurückgesetzt" (the connection was resetted by cummunication partner).
And I noticed (not related to the latest changes) some unexpected behaviour: when you add a file to the queue from ncmpc, and the player is paused, it gets unpaused. 
Let me expresse here my admiration for your dedication to this project - I read through the thread in rapsberry-pi org, and I do no remember a project maintained so constantly by one single person with this kind of effort. Thank you for this great project!!

**Comment by ejurgensen** [comment]
If you really read the entire thread then you certainly have some stamina as well! Just to be sure - when you say you installed the new version, you mean the branch with chme's modifications, right?

And yes, a library of that size will require some scan time.

**Comment by LordMyschkin** [comment]
You pointed me to the right version, it is the one with chme's modifications. Will test them later at home -I am a little bit sad it still is not as responsive as mpd on the same rpi, but I had not much time to play around with...

**Comment by LordMyschkin** [comment]
well - somehow, this version does not accept connections on the mpd port (configured to 6601) after some hours (running for about 18 hours now); neither remote  (Cantata-client from windows) nor local (mpc and ncmpc). Tho log file tells nothing (log-level) - will increase verbosity to debug-level and see if I can reproduce the problem.

**Comment by chme** [comment]
@LordMyschkin it is probably to late ... but if you still can, make a backup of your songs3.db file. The changes in https://github.com/ejurgensen/forked-daapd/tree/chme-mpddb will upgrade the db file and will make it incompatible with current master. 

In my tests i did not encounter any connection problems, would be great if you can get a debug log for this issue.

**Comment by LordMyschkin** [comment]
@chme don't worry - I can rebuild the database with current master if I really will step down. I restarted my rPi with IPv6 enabled and forked-daadp with IP6 enabled - but that was no clue either.
I have no real problems, but short disconnections in ncmpc locally on the Raspi, and it works flawlessly remotly on the "Remote" in IOS. But in your version, I fail to get any database entry via any remote MPC client in Windows (tried Cantata, Auremo and Ario on Win7 and Win8.1) or IOS (MpAD and MpOD). Log tells nothing even in debug mode. What is you exact test environment - may it be a network issue? 
Last entry from log is 
 db: Starting query 'SELECT f.* FROM files f WHERE f.disabled = 0 AND (f.artist LIKE '%%' OR f.album LIKE '%%' OR f.title LIKE '%%') ORDER BY f.title_sort ASC;

**Comment by LordMyschkin** [comment]
One last remark on this closed thread: I downgraded, rebuild the database in about 2500 seconds, no problems at all in a 4pv4 environement on jessie-Raspian.

**Comment by chme** [comment]
Strange, the connection problems did not happen on my setup (rpi2 with raspbian wheezy, mpd clients mpc, sonata (local and from my laptop running xubuntu 14.04), mPod and MPDroid).

I expected at least an error log that the socket could not be bound for the (forked-daapd) mpd port.
I added a commit to the mpddb branch that aligns the handling of IPv6/IPv4 to how it is done for dacp/daap (fallback to IPv4 if IPv6 failed in 343b23a).

Where there any entries in the log starting with [MPD] ?
Which mpd client lead to the high cpu load?

**Comment by LordMyschkin** [comment]
Well, there was some reaction from the clients I connected (i tried some of them, I can't remember wich one was the last, maybe cantata). 
I was abe to get the current playlist and sometimes to switch outputs - but I never got into browsing my directories.
Maybe that forked-dapd could not swallow my rather large collection?
I looked for mpd: entries in the log - they give no clue, status messages, MPD message: playlistinfo "-1",   mpd: Command 'playlistinfo' called with pos < 0 (arg = '-1'), ignore arguments and return whole queue and so on...

**Comment by chme** [comment]
I think if found the cause. There was an error in the db upgrade logic (v18.01 to v19), it should be fixed by 26d6c3a. I will do some more tests over the weekend.

**Comment by LordMyschkin** [comment]
:-) Did I tell you i rebuild the database from scratch with your version? Maybe that ist the difference between our two settings.
If I can help (providing you a private key for ssh for my raspberry btw.), just let me know! I am really sad I cannot contribute to this project by programming because of lacking skills....

**Comment by chme** [comment]
Too bad, i really hoped this would be the solution ...

If you can test with the latest changes from https://github.com/chme/forked-daapd/tree/mpddb with rebuilding the db, that would be really great. 
I did not find anything that would explain why you encountered these problems, so i expect it will still not work on your setup. If it fails, can you send me your db file (e.g. via mail to christian.meffert AT googlemail.com)? That should hopefully be enough to narrow down the cause for this problem.

**Comment by LordMyschkin** [comment]
I am rebuilding now , will send you the success message and - if there remain any problems - the link to the db (about 50 MBs unzipped, even zipped not the size to mail.) as soon as we are done here...
I'd love to get the best of mpd and of itunes of my raspberry pi. :-)
