### ISSUE TITLE
[enhancement] Player should use the music's native sample rate / bit rate

### ISSUE THREAD

**Issue by adamdmoss** [ejurgensen/forked-daapd#395]
I've walked the code and it *looks* like everything is transcoded to 44100/16.
Would be nice if 48KHz played back at 48KHz, perhaps even 24bit-as-24bit, etc.
I think I vaguely recall that 44100/16 is an AirPlay limit, but it'd be nice if local jukebox mode wasn't limited in the same way.
Cheers!

**Comment by ejurgensen** [comment]
Yes, that is correct, everything is locked to 44100/16 right now. It's would be a bit of an undertaking to support multiple quality levels, so I don't think it is anything I can do for the time being. I am, however, inching in that direction, for instance there is a more flexible transcoding module in the pipeline.

**Comment by adamdmoss** [comment]
Hi Espen, would it help prioritize this if I paid?  Thought it doesn't hurt to ask. :)

**Comment by ejurgensen** [comment]
It's great you push on this. I prefer making changes that are in demand, of course. I'm not immune to money, but it would need to be a pretty significant dose. You could try something like bountysource.com, maybe that will be a cheaper/faster avenue. Not that I can guarantee I will accept PR's on this - I would have to agree with the way the changes are made, since I would have to maintain it.

In any case, it is great you show interest in this. During the holiday I will look at how to get started with this. If I find a good way, I will probably also finish.

**Comment by AlekLT** [comment]
I'd also love to see this.

**Comment by moretocome** [comment]
Bumping this for interest.

I just ordered a 32bit/384KHz DAC for my Rpi, and I was planning on using forked-daapd for my music server. But I might change my mind if this means I am only able to output 44100Hz/16bit sample rate/bit rate.

I would also really love to see this feature implemented.

And thanks anyway for this otherwise sweet piece of software. I really like that I am able to output music from the server with Sonata and from the local client machine with Rythmbox.

**Comment by moretocome** [comment]
I have switched to a native MPD install and disabled MPD in forked-daapd to avoid downsampling. @ejurgensen please update if you ever implement native samplerate/bit rate playback :)

**Comment by ejurgensen** [comment]
Sorry to say it is not right around the corner, at least from my side. It would be great to have, but doing it properly requires significant changes.

**Comment by bendschs** [comment]
+1 i also would love to see that feature.
in the meantime it would also be nice if it would be possible to specify the sampling rate of the mpd player in the config file. at the moment it sems to be 128  kbps and 44.1 kHz. especially the bitrate seems to be quite low.

cheers
bendsch

**Comment by jompjomp** [comment]
> +1!
> i also would love to see that feature.
> in the meantime it would also be nice if you would be able to specify the sampling rate of the mpd player in the config file. at the moment it sems to be 128 kbps and 44.1 kHz. especially the bitrate seems to be quite low.
> 
> cheers
> bendsch

 I’m also with bendsch, a way to increase the bitrate would be very desirable.

**Comment by ejurgensen** [comment]
This issue is pretty old, but in case anyone is still around, I would like to announce that forked-daapd now does support native sample rate and bit rate. It should work with ALSA and Pulseaudio, and in theory also with Airplay if a non-44100/16 Airplay 1 device exists. For Chromecast the quality is fixed at 48000/16, and no resampling will take place if the source is the same quality.

The changes made are fairly significant and I have just pushed them to the master branch. There are probably a number of new bugs as a result of that.

I will close the issue since the feature is made.

**Comment by bendschs** [comment]
thanx for implementing this. my mpd-clients still show 128 kb/sec and 16-bit. I am on version 27.2. Is there any additional configuration needed for true bitrate output? 

I use pulseaudio on a local output device.

cheers
bendsch

![Bildschirmfoto 2021-01-08 um 20 04 38](https://user-images.githubusercontent.com/17085451/104054513-8ecf9580-51ed-11eb-91b1-9f0d94aee247.png)

**Comment by ejurgensen** [comment]
I think it is just the presentation in the mpd clients that is incorrect, might be related to issue #959. @chme how do you see this?

**Comment by bendschs** [comment]
ok, in the webinterface i see full bitrates and frequencies. are these the actual parameter the player is playing the files with or are these plain file informations?
![Bildschirmfoto 2021-01-09 um 00 00 21](https://user-images.githubusercontent.com/17085451/104073442-f990c900-520d-11eb-98d6-e42dbac7ab67.png)

**Comment by ejurgensen** [comment]
That is the source quality, the actual playback quality is per output, so it isn't always a single quality. Generally local audio (the sound card) will be full source quality, while Airplay speakers are 44100/16, Chromecast is 48000/16 and mp3 streams are the quality that is set in the config. I think you can check the sound card quality from the log, don't remember that exactly.

**Comment by ubik3000** [comment]
> This issue is pretty old, but in case anyone is still around, I would like to announce that forked-daapd now does support native sample rate and bit rate. It should work with ALSA and Pulseaudio, and in theory also with Airplay if a non-44100/16 Airplay 1 device exists. For Chromecast the quality is fixed at 48000/16, and no resampling will take place if the source is the same quality.
> 
> The changes made are fairly significant and I have just pushed them to the master branch. There are probably a number of new bugs as a result of that.
> 
> I will close the issue since the feature is made.

Hello
First of all tahnk you for owntone, it is nice. "For Chromecast the quality is fixed at 48000/16, and no resampling will take place if the source is the same quality." Why this limitation? I am playing some 44.1 KHz local music/online radio and the Chromecast Audio will output it in 48KHz in owntone. Upsampling from 44.1 to 48KHz is not a good idea... And I know for sure that with DI.fm Android app, Chromecast will output correctly in 44.1, just like the original source (di.dm online radio). I also know tha Chromecast is capable of outputting at maximum into 24/96...

**Comment by ejurgensen** [comment]
There's two things that make variable sample rates for Chromecast (and Airplay) challenging:
1. Let's say you have a queue with a 48khz track and then a 44.1khz track. As the design is today, we would need the Chromecast speakers to change sample rate mid playback, without any playback pause, because we don't want them to get behind other speaker types. I don't know if that is possible, but I wouldn't think so. Even with ALSA it is just barely possible. So the way to support this would be to stop all speakers, wait for them to call back that they are ready for a new sample rate, and then resume. That's quite challenging to implement.
2. Since I don't have many devices to test with, it's dangerous to make assumptions about what they are capable of. Ideally, there would be a request to ask the speaker. Maybe there is, I wouldn't know.

**Comment by ubik3000** [comment]
Hello,

In this case shouldn't 44100 Hz sampling rate for Chromecast Audio be a more sensible default, as the vast majority of music is sampled at 44100 Hz (Audio CD, Apple Music, Spotify, etc).

Thanks,
Cristian

**Comment by ejurgensen** [comment]
I think the 48k came from Chromium, but since the stream is a lossy Opus-stream, I think there is more that goes into the playback quality than the sample rate. I'm not even sure the sample rate plays much role in this context, because the encoder may instead be targeting a certain bitrate. The encoding is done by ffmpeg, and I don't remember exactly what it does. OwnTone doesn't currently tell ffmpeg which bitrate to use, so ffmpeg decides.

@whatdoineed2do made PR #819 for configurable bitrate. I did reject that, however, but we can take it up again. Would have to be in another form though (use settings instead of config file), and we would need to test it's actual effect.

I guess another question is if the Chromecast speaker's internal sample rate is in fact 48k.

**Comment by ubik3000** [comment]
"I guess another question is if the Chromecast speaker's internal sample rate is in fact 48k."
I have Chromecast connected via optical output to a DAC that displays the incoming sample rate. In DI.fm and Apple Music apps Chromecast is setup correctly to 44.1 KHz sample rate. Also, in some scenarios, output sampling rate of Chromecast is 48KHz.
