### ISSUE TITLE
web interface speaker selection

### ISSUE THREAD

**Issue by frankusb** [ejurgensen/forked-daapd#978]
On the web interface, if the number of speakers exceeds the user's vertical height of their browser, it is not scrollable and they cannot access speakers off screen.

**Comment by chme** [comment]
Not sure what is wrong here. The `overflow: scroll` property is set, to force showing a scrollbar (and make the menu scrollable). @ejurgensen reported something similar for the top navbar menu. Do you experience the problem there as well?

**Comment by ejurgensen** [comment]
Scrolling works fine on my iPhone, but in desktop Chrome and Edge I can reproduce the issue (there is no scrollbar). I think you can reproduce it easily by just modifying speaker_enumerate() in player.c so that it loops a bunch of extra times.

When I tried on iPhone I encountered an other issue which is also when there are many speakers. This issue is that when you open the speaker selection menu it is not possible to close it again. Below are screenshots from scrolling all the way  to the top and all the way to the bottom. The open/close bar seems to be gone. Let me know if you want a separate issue opened on this.

Top             |  Bottom
:-------------------------:|:-------------------------:
![IMG-3658](https://user-images.githubusercontent.com/1156686/80796025-71e2bd00-8b9e-11ea-846c-5a34c5a99827.PNG) | ![IMG-3659](https://user-images.githubusercontent.com/1156686/80796026-727b5380-8b9e-11ea-9bd6-283bef6d022c.PNG)

Oh the joys of web development :-)

**Comment by chme** [comment]
I've made some changes to the navbar menus to hopefully force showing missing scrollbars. Could you please test again #980 (there is also a zipped htdocs folder attached)?

**Comment by ejurgensen** [comment]
Excellent! - with your fix I have no issue with scrolling in Chrome/Edge, and the navbar is present in Safari/iPhone, so that issue is fixed as well.

**Comment by frankusb** [comment]
Is a source update and binary replacement all that's required to get this change? I am not able to scroll speaker selection after doing git pull, make, sudo cp src/forked-daapd /usr/sbin/forked-daapd.

**Comment by ejurgensen** [comment]
You also need to update the html. I recommend using `make install` instead of cp, that's the proper way. Some more recommendations when running your own build:

1. Remove any packaged version you have installed (to avoid conflicts)
2. Make a small script that you can always run to update your installation (add --enable-spotify, --enable-chromecast etc if you require):
```
git pull
./configure
make
sudo make install
cp /etc/forked-daapd.conf /usr/local/etc/forked-daapd.conf
```
3. Use regular ./configure, so that stuff gets installed to /usr/local. That way you can always later go back to a package. It also avoids /etc/forked-daapd being overwritten by `make install`, so that you can use that as master.

**Comment by frankusb** [comment]
Thank you, I verified that make install did update htdocs. I still do not have scrolling speaker selection on desktop Chrome.

**Comment by frankusb** [comment]
Shift reload in Chrome fixed the stale data. Sorry for the confusion.

**Comment by holly79** [comment]
I used the latest build from [here](https://github.com/ejurgensen/forked-daapd/issues/734#issuecomment-623577112) and I have no scroll bar in Chrome/Firefox on Mac. So I can only select my speaker on the top if I scale down the web site.

**Comment by ejurgensen** [comment]
That build doesn’t include the scroll bar fix

**Comment by holly79** [comment]
Ok, thanks. I can wait until it is in a new release.
